/*
*28/02 - file used to store data used in the project, includes large arrays
*/

"use strict";

const available_districts = [
  "blackriver",
  "flacq",
  "grandport",
  "moka",
  "pamplemousses",
  "plainewilhems",
  "portlouis",
  "rivieredurempart",
  "savanne",
];

let available_localities = [
  "16eme mile",
  "albion",
  "allee brillant vacoas",
  "amaury",
  "amitie",
  "anse jonchee",
  "anse la raie",
  "arsenal",
  "baie du cap",
  "bain boeuf",
  "bain des dames",
  "balaclava",
  "balisson",
  "bambous",
  "bananes",
  "batimarais",
  "beau bassin",
  "beau bois",
  "beau champ flacq",
  "beau sejour belle-rose",
  "beau vallon",
  "bel air",
  "bel etang",
  "bel ombre",
  "bell village",
  "belle bue allandy",
  "belle etoile",
  "belle mare",
  "belle rose  ( q bornes )",
  "belle vue harel",
  "belle vue maurel",
  "belle vue pilot",
  "belvedere ( beau bassin )",
  "blue bay",
  "bois cheri",
  "bois des amourettes",
  "bois pignolet",
  "bois rouge",
  "bon  acceuil",
  "bonne mere",
  "bonne terre",
  "boulet rouge",
  "bramsthan",
  "brisee verdiere",
  "calebasses",
  "calodyne",
  "camp carol kenya",
  "camp chapelon",
  "camp de masque pave",
  "camp de masque",
  "camp des embrevades",
  "camp diable",
  "camp fouquereaux",
  "camp ithier",
  "camp levieux ( r hill )",
  "camp thorel",
  "canal dayot",
  "candos q bornes",
  "candos vacoas",
  "canot",
  "cap malheureux",
  "caroline bel air",
  "carreau laliane",
  "cascavel",
  "cassis",
  "castel vacoas",
  "central flacq",
  "chamarel",
  "chamouny",
  "chemin grenier",
  "choisy - baie du cap",
  "cinq arpents",
  "cite atlee",
  "cite chebel",
  "cite l-oiseau",
  "cite la cure",
  "cite malherbes",
  "cite richelieu",
  "cite vallijee",
  "clemencia",
  "closel",
  "cluny",
  "congomah",
  "constance",
  "coromandel - r.hill",
  "cote d-or",
  "cottage",
  "creve coeur",
  "curepipe",
  "d-epinay",
  "dagotiere",
  "deep river beau champ",
  "deux bras- new grove",
  "deux freres",
  "dubreuil",
  "eau coulee",
  "ebene",
  "ernest florent",
  "esperance piton",
  "esperance trebuchet",
  "flic-en-flac",
  "floreal",
  "fond du sac",
  "forest side",
  "fuel village",
  "gentilly- moka",
  "glen park",
  "goodlands",
  "grand bassin",
  "grand bay",
  "grand bel air",
  "grand bois",
  "grand gaube",
  "grand sable",
  "grande pointe aux piments",
  "grande riviere sud est",
  "gros billot",
  "gros bois",
  "gros cailloux",
  "haute rive",
  "helvetia",
  "henrietta",
  "hermitage phoenix",
  "highlands",
  "hollyrood",
  "ilot",
  "isidore rose",
  "khoyratty",
  "l-assurance",
  "l-escalier",
  "l-esperance q.militaire",
  "la caverne",
  "la chaumiere",
  "la ferme bambous",
  "la flora",
  "la gaulette",
  "la laura (bel air)",
  "la laura saint pierre",
  "la marie",
  "la mivoie",
  "la preneuse",
  "la rosa",
  "la saline",
  "la sourdine",
  "lallmatie",
  "latapie",
  "le bouchon",
  "le chaland",
  "le goulet",
  "le hochet",
  "le morne",
  "les casernrs curepipe",
  "les mariannes",
  "lesur",
  "long mountain",
  "lower vale",
  "mahebourg",
  "mapou leclezio",
  "mare d-albert",
  "mare gravier",
  "mare longue",
  "mare tabac",
  "medine bambous",
  "medine camp de masque",
  "melrose",
  "melviile",
  "mesnil",
  "midlands",
  "mlle laure",
  "mme azor",
  "moka",
  "mon choisy",
  "mon gout",
  "mon loisir",
  "mon songe",
  "mont  simonet",
  "mont blanc",
  "mont ida",
  "mont roches",
  "montagne blanche",
  "montagne ory",
  "morc saint andre",
  "mount",
  "new grove",
  "notre dame",
  "nouvelle decouverte",
  "nouvelle france",
  "pailles",
  "palma",
  "palmar",
  "pamplemousses",
  "pavillon",
  "pellegrin sebastopol",
  "pereybere",
  "petit bel air",
  "petit camp",
  "petit paquet",
  "petit raffray",
  "petit sable",
  "petit verger p aux sables",
  "petit verger saint pierre",
  "petite julie",
  "petite pointe aux piments",
  "petite retraite",
  "petite riviere noire",
  "petite riviere",
  "phoenix",
  "plaine chanpagne",
  "plaine des papayes",
  "plaine des roches",
  "plaine lauzun",
  "plaine magnien",
  "plaine verte",
  "plaisance rose hill",
  "pointe aux feuilles",
  "pointe aux sables",
  "pointe d-esny",
  "pointe des lascars",
  "port-louis",
  "poste de flacq",
  "poste lafayette",
  "providence bois des amourettes",
  "providence la porte",
  "providence quartier militaire",
  "quartier militaire",
  "quatre cocos",
  "quatre soeurs",
  "quatre-bornes",
  "quay d",
  "queen victoria",
  "quinze cantons",
  "ramp le moirt",
  "reduit",
  "reunion maurel",
  "riambel",
  "riche en eau",
  "riche terre",
  "richemare",
  "riviere baptiste st pierre",
  "riviere des anguilles",
  "riviere des creoles",
  "riviere des galets",
  "riviere du poste",
  "riviere du rempart",
  "riviere noire",
  "roche bois",
  "roche terre",
  "roches brunes",
  "roches noires",
  "rose belle",
  "rose-hill",
  "rouillard",
  "saint aubin",
  "saint francois",
  "saint hubert",
  "saint joseph",
  "saint julien village",
  "saint martin r-hill",
  "saint paul",
  "saint pierre",
  "sainte croix",
  "sauveterre",
  "sebastopol",
  "sodnac",
  "solferino",
  "solitude",
  "sottise",
  "souillac",
  "stanley",
  "surinam",
  "tamarin",
  "terre rouge",
  "tombeau bay",
  "tour koenig",
  "tranquebar",
  "trefles",
  "trianon",
  "triolet",
  "trois boutiques triolet",
  "trois boutiques union vale",
  "trou aux biches",
  "tyack",
  "union park",
  "upper dagotiere",
  "upper vale",
  "vacoas",
  "valentina",
  "valetta",
  "vallee des pretres",
  "vallee pitot",
  "verdun",
  "vieux grand port",
  "villebague",
  "villenoire",
  "vuillemin q.militaire",
  "wootun",
  "yemen",
];

export { available_districts, available_localities };
